name: test timeout
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up nodejs
        run: |
          echo "########################################"
          echo "Vas a iniciar con la espera de 2 minutos"
          echo "########################################"
          sleep 45
          echo "Bien!, vas a 45 segundos"
          sleep 10
          echo "Bien, solo faltan 5 segundos"
          sleep 60
          echo "si ves esto es por no funciono el action"


      